name: skin_solver
description: A new Flutter project.

publish_to: 'none' 

version: 2.0.0+30

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  app_tracking_transparency: ^2.0.6 # Added ATT dependency
  adjust_sdk: ^5.0.2 # Added Adjust SDK
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cloud_firestore: 5.4.4
  firebase_auth: 5.3.1
  firebase_core: 3.6.0
  flutter_animate: 4.5.0
  google_fonts: 6.1.0
  provider: 6.1.2
  purchases_flutter: 8.1.2
  rxdart: 0.27.7
  shared_preferences: 2.3.2
  stream_transform: ^2.0.0 # Added missing dependency
  from_css_color: ^2.0.0 # Added missing dependency
  url_launcher: 6.3.0
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.2
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  image: 4.2.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
